### ISSUE TITLE
Migration to MavenCentral

### ISSUE THREAD

**Issue by l3nz** [ari4java/ari4java#171]
See https://www.marcogomiero.com/posts/2021/move-libray-jcenter-to-maven/

**Comment by grahambrown11** [comment]
Thanks @l3nz I had it on my personal list to look at since Bintray are sunsetting...
I was wondering about using GitHub Packages, but maybe maven central is better...

**Comment by l3nz** [comment]
Maven Central is a huge PITA to set up

**Comment by grahambrown11** [comment]
@l3nz I requested ch.loway.oss.ari4java at sonatype but they said there already a staging repository for ch.loway and someone with a deployer role needs to comment on my ticket [OSSRH-65133](https://issues.sonatype.org/browse/OSSRH-65133?page=com.atlassian.jira.plugin.system.issuetabpanels:all-tabpanel)

**Comment by grahambrown11** [comment]
I've changed the group id to `io.github.ari4java` which is now published to Maven Central
