### ISSUE TITLE
Statement Fail - ariClient.playbacks().stop(playbackId).execute() - (DELETE /ari/playbacks HTTP/1.1)

### ISSUE THREAD

**Issue by adora-tech** [ari4java/ari4java#172]
Hello all,

Most of the time the line below is executed successfully,

`ariClient.playbacks().stop(playback.getId()).execute();`

but there are times when it fails.

Following the execution, // ("AAAAA" and "BBBBB" are to explain)

```
try {
     System.out.println ("AAAAA");
     ariClient.playbacks().stop(playback.getId()).execute();
     System.out.println ("BBBBB");
} catch (RestException restException) {
     restException.printStackTrace ();
}
```

I get two situations, with trace enabled:

A bad situation in which I see in logs printed only "AAAAA" and I do not see an exception thrown or other errors, which I do not expect.

**===== BAD =====**

In ari4java console log:

> 2021-03-01 14:58:46.533 TRACE: HTTP Request:
> DELETE /ari/playbacks/bd5704f8-9aa0-476c-8138-aef0f86935e5 HTTP/1.1
> host: 192.168.1.79
> connection: close
> authorization: *****
> 2021-03-01 14:58:46.533 DEBUG: Sync Action - DELETE to /ari/playbacks/bd5704f8-9aa0-476c-8138-aef0f86935e5
> 2021-03-01 14:58:46.533 DEBUG: HTTP Connect uri: http://192.168.1.79:8088/
> 2021-03-01 14:58:46.535 DEBUG: HTTP connected
> 
> **//HTTP Response is missing...**
> 
> **//ARI Message arrives when file playback ends... (for example, after 5 seconds from failed playback stop)**
> 2021-03-01 14:58:51.567 DEBUG: Received Message - TextWebSocketFrame
> 2021-03-01 14:58:51.567 TRACE: WS Frame:
> {
>   "type": "PlaybackFinished",
>   "timestamp": "2021-03-01T14:58:53.309+0200",
>   "playback": {
>     "id": "bd5704f8-9aa0-476c-8138-aef0f86935e5",
>     "media_uri": "sound:adora/key-selection",
>     "target_uri": "channel:1614603507.350",
>     "language": "ro",
>     "state": "done"
>   },
>   "asterisk_id": "00:0c:29:2b:be:3b",
>   "application": "ari-app"
> }

In Asterisk console, **there is no "Playback stopped" line**:

>     -- Executing [0799XXXYYY@stasis-ari-app:1] Stasis("PJSIP/9999-000000b0", "ari-app") in new stack
>        > 0x2acd70023030 -- Strict RTP learning after remote address set to: 192.168.1.109:40046
>        > 0x2acd70023030 -- Strict RTP switching to RTP target address 192.168.1.109:40046 as source
>     -- <PJSIP/9999-000000b0> Playing 'adora/intro.slin' (language 'ro')
>        > 0x2acd70023030 -- Strict RTP learning complete - Locking on source address 192.168.1.109:40046
>     -- <PJSIP/9999-000000b0> Playing 'adora/announce.slin' (language 'ro')
>     -- <PJSIP/9999-000000b0> Playing 'adora/key-selection.slin' (language 'ro')
>     -- Executing [h@stasis-ari-app:1] NoOp("PJSIP/9999-000000b0", "") in new stack

And a good situation in which it is executed successfully and I see in logs "AAAAA" and "BBBBB".

**===== GOOD =====**

In ari4java console log:

> 2021-03-01 16:37:51.258 TRACE: HTTP Request:
> DELETE /ari/playbacks/d11b883b-b65c-47d2-81d2-2c50e0c7614a HTTP/1.1
> host: 192.168.1.79
> connection: close
> authorization: *****
> 2021-03-01 16:37:51.258 DEBUG: Sync Action - DELETE to /ari/playbacks/d11b883b-b65c-47d2-81d2-2c50e0c7614a
> 2021-03-01 16:37:51.258 DEBUG: HTTP Connect uri: http://192.168.1.79:8088/
> 2021-03-01 16:37:51.262 DEBUG: HTTP connected
> 
> **//Here we have an HTTP Response**
> **2021-03-01 16:37:51.263 TRACE: HTTP Response:
> HTTP/1.1 204 No Content
> Server: Asterisk
> Date: Mon, 01 Mar 2021 14:37:51 GMT
> Connection: close
> Cache-Control: no-cache, no-store
> Content-Length: 0**
> 
> 2021-03-01 16:37:51.264 DEBUG: Received Message - TextWebSocketFrame
> 2021-03-01 16:37:51.265 TRACE: WS Frame:
> {
>   "type": "PlaybackFinished",
>   "timestamp": "2021-03-01T16:37:51.270+0200",
>   "playback": {
>     "id": "d11b883b-b65c-47d2-81d2-2c50e0c7614a",
>     "media_uri": "sound:adora/key-selection",
>     "target_uri": "channel:1614609455.352",
>     "language": "ro",
>     "state": "done"
>   },
>   "asterisk_id": "00:0c:29:2b:be:3b",
>   "application": "ari-app"
> }

In Asterisk console, there is "Playback stopped" line:

> -- Executing [0799XXXYYY@stasis-ari-app:1] Stasis("PJSIP/9999-000000b1", "ari-app") in new stack
>        > 0x2accec017510 -- Strict RTP learning after remote address set to: 192.168.1.109:40048
>        > 0x2accec017510 -- Strict RTP switching to RTP target address 192.168.1.109:40048 as source
>     -- <PJSIP/9999-000000b1> Playing 'adora/intro.slin' (language 'ro')
>        > 0x2accec017510 -- Strict RTP learning complete - Locking on source address 192.168.1.109:40048
>     -- <PJSIP/9999-000000b1> Playing 'adora/announce.slin' (language 'ro')
>     -- <PJSIP/9999-000000b1> Playing 'adora/key-selection.slin' (language 'ro')
> **[Mar  1 16:37:51] NOTICE[4981][C-000000b2]: res_stasis_playback.c:273 playback_final_update: 1614609455.352: Playback stopped for sound:adora/key-selection**
>     -- <PJSIP/9999-000000b1> Playing 'adora/tt-codezone_MIXDOWN.slin' (language 'ro')
>     -- Executing [h@stasis-ari-app:1] NoOp("PJSIP/9999-000000b1", "") in new stack

	

At first glance it seems that the action following the statement does not leave the application and does not reach the Asterisk PBX.
I initiate over 25 calls to reproduce this behavior.
I use this statement in an IVR, after I receive a DTMF tone, I have to stop the current playback.

I made a tcpdump capture on the server and a wireshark capture on the client and I didn't see the action:
**DELETE /ari/playbacks/bd5704f8-9aa0-476c-8138-aef0f86935e5 HTTP/1.1**
in the communication between server and client.
This is the reason why I opened this issue.

Thank you,
Iulius

**Comment by grahambrown11** [comment]
@adora-tech thanks for the detailed issue. 

- Please confirm if this is an intermittent problem.
- Do you perhaps have an easy way to reproduce?
- What version of Asterisk are you using?

Thanks

**Comment by adora-tech** [comment]
I use Asterisk 18.2.0
Yes, it is an intermittent problem, at over +-30 successful actions, a wrong one appears.
I will look for an easy way to reproduce it, and I will come back with an answer.

Thank you

**Comment by adora-tech** [comment]
@grahambrown11 thank you for help!

Trying to simplify things to find a simple way to reproduce the issue, I noticed that I have a problem with threads.

So, I noticed in the logs a limit of 24 threads and once I reached this limit I noticed the issue described above:

`14:01:25.280 [main] DEBUG io.netty.channel.MultithreadEventLoopGroup - -Dio.netty.eventLoopThreads: 24`

![netty_threads](https://user-images.githubusercontent.com/58594685/111876779-ff8eed00-89a8-11eb-9c2e-0bc028601753.jpg)

How I got here?
I wrote code to manage the subscription and unsubscription from certain specific ARI events in different state machines.
In doing so, I approached the reception of events differently, intercepting the events and then delivering them where they are needed in the code.

I do,

```
AriCallback<Message> ariCallback = new AriCallback<Message>() {
            @Override
            public void onSuccess(Message message) {
                **eventService.notifyListeners(message);**
            }

            @Override
            public void onFailure(RestException e) {
                log.error("Error: {}", e.getMessage(), e);
            }
        };
        try {
            **ariClient.eventsCallback(ariCallback);**
        } catch (ARIException ariException) {
            log.error("ARI Client Message: " + ariException.getMessage());
            ariClient.cleanup();
        }
```

instead of:

```
final **ExecutorService threadPool = Executors.newFixedThreadPool(10);**
        ari.eventsCallback(new AriWSHelper() {
            @Override
            public void onSuccess(Message message) {
                **threadPool.execute(() -> super.onSuccess(message));**
            }
```

So, I missed ExecutorService part.

Once I used ExecutorService like in your example, everything is ok now.
This issue can be closed.

Thank you,
Iulius

**Comment by grahambrown11** [comment]
Great thanks for the feedback, multi-threaded applications can be troublesome.

I see you're using Spring, you should consider using `org.springframework.scheduling.concurrent.ThreadPoolTaskExecutor`.
I tried to keep the examples in native Java, but if you're using Spring that would be a better approach...

Here is some code example:
`ThreadPoolConfig.java`
```java
@Configuration
public class ThreadPoolConfig {
    @Bean
    public ThreadPoolTaskExecutor ariTaskExecutor() {
        ThreadPoolTaskExecutor pool = new ThreadPoolTaskExecutor();
        pool.setCorePoolSize(5);
        pool.setMaxPoolSize(10);
        pool.setThreadNamePrefix("ARIExec-");
        return pool;
    }
}
```
`ARIComponent.java`
```java
@Component
public class ARIComponent {

    @Value("${ari.app}")
    private String app;
    @Value("${ari.url}")
    private String url;
    @Value("${ari.user}")
    private String user;
    @Value("${ari.pass}")
    private String pass;

    private final ThreadPoolTaskExecutor ariTaskExecutor;

    @Autowired
    public ARIComponent(ThreadPoolTaskExecutor ariTaskExecutor) {
        this.ariTaskExecutor = ariTaskExecutor;
    }

    @PostConstruct
    public void init() throws ARIException, URISyntaxException {
        ARI ari = AriFactory.nettyHttp(
                url,
                user,
                pass,
                AriVersion.ARI_6_0_0,
                app);
        ari.events().eventWebsocket(app).execute(new AriCallback<Message>() {
            @Override
            public void onSuccess(Message result) {
                ariTaskExecutor.execute(() -> {
                    // code to handle event...
                });
            }
            @Override
            public void onFailure(RestException e) {
                ariTaskExecutor.execute(() -> {
                    // code to handle exception...
                });
            }
        });
    }

}
```

I will however put it on the back burner to check the underlying framework to see if there is a way to avoid the problem...
