### ISSUE TITLE
Update to Netty 4.1.64 to prevent StackTraces in logs when using Java >= 11 

### ISSUE THREAD

**Issue by jbreitung** [ari4java/ari4java#176]
As already mentioned in https://github.com/netty/netty/issues/7817, some log messages with unimportant StackTraces are generated by Netty because a reflective method is called that no longer exists since Java 11. With https://github.com/netty/netty/pull/11164 small changes were made in Netty that these log messages should no longer occur.

Since these are minor changes, there should be nothing against upgrading to Netty 4.1.64 at the next opportunity.

**Comment by grahambrown11** [comment]
#177 Merged and released 0.13.0
