### ISSUE TITLE
[BUG] ARI RTPStats Decode exception for remote_ssrc

### ISSUE THREAD

**Issue by chingucoding** [ari4java/ari4java#180]
When decoding the RTPStat result, sometimes an exception can occur:

```
Decoding JSON: Numeric value (3175369733) out of range of int (-2147483648 - 2147483647)
 at [Source: (String)"{
  "txcount": 7,
  "rxcount": 182,
  "txploss": 0,
  "rxploss": 0,
  "local_ssrc": 1176001751,
  "remote_ssrc": 3175369733,
  "txoctetcount": 681,
  "rxoctetcount": 7360,
  "channel_uniqueid": "16dcbc11-6f83-45d0-a25c-ac7958bb37fc",
  "txjitter": 0.00014278829504509212,
  "rxjitter": 0.0,
  "remote_maxjitter": 0.0,
  "remote_minjitter": 0.0,
  "remote_normdevjitter": 0.0,
  "remote_stdevjitter": 0.0,
  "local_maxjitter": 0.00022334546099132789,
  "local_minjitter": 5.1856040954589844e-6,
  "loc"[truncated 409 chars]; line: 7, column: 28] (through reference chain: ch.loway.oss.ari4java.generated.ari_6_0_0.models.RTPstat_impl_ari_6_0_0["remote_ssrc"]) 
```

The RFC does not specify if the (remote_)ssrc is unsigned or not so the value 3175369733 can be a valid value.

**Comment by grahambrown11** [comment]
The Swagger definition has that as an `int` whose max value is 2147483647, so 3175369733 is larger... 
I think this class has limited use so I can tweak the code generator to rather use a `Long` instead of an `Integer` for the `..._ssrc` fields

**Comment by chingucoding** [comment]
Just checked and indeed, the swagger documentation claims it is an int. It seems that there is a discreptancy between the source code and the Swagger definition, e.g. internally the RTP Statistics struct only uses unsigned integers while the Swagger documentation says it's just `int`. But that is an Asterisk issue, feel free to close this issue now since it seems that your d4dcbdd seems to solve this issue. Thank you for your help!

**Comment by grahambrown11** [comment]
0.15.0 is being released hopefully it'll help you

**Comment by chingucoding** [comment]
Just tested this and I can confirm that the bug is fixed now, thank you!
