### ISSUE TITLE
Netty RedTimeOut

### ISSUE THREAD

**Issue by tushar2369** [ari4java/ari4java#185]
### Discussed in https://github.com/ari4java/ari4java/discussions/184

<div type='discussions-op-text'>

<sup>Originally posted by **tushar2369** April 13, 2022</sup>
When i playback start after 30 second call auto rejected cause by: io.netty.handler.timeout.ReadTimeoutException: null</div>

**Comment by grahambrown11** [comment]
@tushar2369 could you please provide some more information and a stacktrace

**Comment by tushar2369** [comment]
```
if ("Up".equals(message.getChannel().getState()) && message.getChannel().getId().equals(state.channel1)) {
    // the channel state has changed to Up and is channel1 in the State object ...
    // this occurs in the startCall flow, when the phone answers we want to create a bridge and add the channel
    // then create a channel for the to number stored in the State object
    logger.debug("Channel 1 answered, create bridge and add channel...");
    try {
        System.out.println("Playback start : ");
        ChannelsPlayWithIdPostRequest pka=  ari.channels().playWithId(message.getChannel().getId(),
                String.valueOf(Math.random()*100+12),"sound:/var/lib/audio1");
        Playback playback=pka.execute();
        System.out.println("Playback state : "+playback.getState());
    } catch (Exception e) {
        System.out.println("Error Playback: "+e.getMessage());
        e.printStackTrace();
    }
    try {
        createBridgeAndAddChannel1(state);
    } catch (RestException e) {
        logger.error("Error creating bridge", e);
        hangupChannel(state.channel1);
        return;
    }
    try {
        state.channel2 = createChannel(state.to, state.from);
        synchronized (lookups) {
            lookups.put(state.channel2, state.id);
        }
        logger.debug("channel2: {}", state.channel2);
    } catch (RestException e) {
        logger.error("Error creating channel2", e);
        hangupChannel(state.channel1);
    }
}
```

 **Note :- This is my code for playing audio . Audio play is ok but after 30 second call hangup and show exception**
@StackTrace

> 09:23:22.495 [nioEventLoopGroup-2-11] DEBUG ch.loway.oss.ari4java.tools.http.NettyHttpClient - HTTP connected
> 09:23:22.495 [nioEventLoopGroup-2-10] DEBUG ch.loway.oss.ari4java.tools.http.NettyHttpClient - HTTP connected
> 09:23:22.653 [nioEventLoopGroup-2-4] DEBUG ch.loway.oss.ari4java.tools.http.NettyWSClientHandler - Received Message - TextWebSocketFrame
> Call Message : ...... ch.loway.oss.ari4java.generated.ari_4_0_0.models.PlaybackStarted_impl_ari_4_0_0@20fd29c1
> 09:23:22.654 [pool-1-thread-4] INFO Asterisk - PlayBack Start ............................
> 09:23:52.499 [nioEventLoopGroup-2-11] WARN io.netty.channel.DefaultChannelPipeline - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
> io.netty.handler.timeout.ReadTimeoutException: null
> 09:23:52.499 [nioEventLoopGroup-2-10] WARN io.netty.channel.DefaultChannelPipeline - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
> io.netty.handler.timeout.ReadTimeoutException: null
> 09:23:52.499 [pool-1-thread-2] ERROR Asterisk - Error creating bridge
> ch.loway.oss.ari4java.tools.RestException: io.netty.handler.timeout.ReadTimeoutException
> 	at ch.loway.oss.ari4java.tools.http.NettyHttpClient.httpActionSyncHandler(NettyHttpClient.java:315)
> 	at ch.loway.oss.ari4java.tools.http.NettyHttpClient.httpActionSyncHandler(NettyHttpClient.java:294)
> 	at ch.loway.oss.ari4java.tools.http.NettyHttpClient.httpActionSync(NettyHttpClient.java:280)
> 	at ch.loway.oss.ari4java.tools.BaseAriAction.httpActionSync(BaseAriAction.java:111)
> 	at ch.loway.oss.ari4java.generated.ari_4_0_0.actions.requests.BridgesAddChannelPostRequest_impl_ari_4_0_0.execute(BridgesAddChannelPostRequest_impl_ari_4_0_0.java:81)
> 	at Asterisk.addChannelToBridge(Asterisk.java:160)
> 	at Asterisk.createBridgeAndAddChannel1(Asterisk.java:151)
> 	at Asterisk.access$1000(Asterisk.java:18)
> 	at Asterisk$Handler.onStasisStart(Asterisk.java:276)
> 	at ch.loway.oss.ari4java.generated.AriWSHelper.onSuccess(AriWSHelper.java:79)
> 	at Asterisk$Handler.lambda$onSuccess$0(Asterisk.java:245)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
> 	at java.lang.Thread.run(Thread.java:748)
> Caused by: io.netty.handler.timeout.ReadTimeoutException: null
> 09:23:52.499 [pool-1-thread-5] ERROR Asterisk - Error creating bridge
> ch.loway.oss.ari4java.tools.RestException: io.netty.handler.timeout.ReadTimeoutException
> 	at ch.loway.oss.ari4java.tools.http.NettyHttpClient.httpActionSyncHandler(NettyHttpClient.java:315)
> 	at ch.loway.oss.ari4java.tools.http.NettyHttpClient.httpActionSyncHandler(NettyHttpClient.java:294)
> 	at ch.loway.oss.ari4java.tools.http.NettyHttpClient.httpActionSync(NettyHttpClient.java:280)
> 	at ch.loway.oss.ari4java.tools.BaseAriAction.httpActionSync(BaseAriAction.java:111)
> 	at ch.loway.oss.ari4java.generated.ari_4_0_0.actions.requests.BridgesAddChannelPostRequest_impl_ari_4_0_0.execute(BridgesAddChannelPostRequest_impl_ari_4_0_0.java:81)
> 	at Asterisk.addChannelToBridge(Asterisk.java:160)
> 	at Asterisk.createBridgeAndAddChannel1(Asterisk.java:151)
> 	at Asterisk.access$1000(Asterisk.java:18)
> 	at Asterisk$Handler.onChannelStateChange(Asterisk.java:327)
> 	at ch.loway.oss.ari4java.generated.AriWSHelper.onSuccess(AriWSHelper.java:57)
> 	at Asterisk$Handler.lambda$onSuccess$0(Asterisk.java:245)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
> 	at java.lang.Thread.run(Thread.java:748)
> Caused by: io.netty.handler.timeout.ReadTimeoutException: null

**Comment by grahambrown11** [comment]
I think there might be 2 issues here:
1. You are not using the correct version of ARI for your Asterisk please check the [Wiki](https://github.com/ari4java/ari4java/wiki/Asterisk-Version-to-ARI-Version) as the data model may have changed and there is a NullPointer happening in the deserialisation.
2. You're not waiting for the event from the playback before executing the next action (adding the channel to the bridge) you should override the `onPlaybackFinished` or you can 1st add the channel to the bridge then execute the playback on the bridge rather than the channel

Hope that helps. If you wouldn't mind sharing your Asterisk version then when I have time I'll try replicate the issue to I can get the library to produce a better error rather than `io.netty.handler.timeout.ReadTimeoutException: null`
