### ISSUE TITLE
Unable to get channelVars

### ISSUE THREAD

**Issue by salesAbhin** [ari4java/ari4java#187]
Hi i am facing an issue while trying to get getChannel var using  the ari 
i am setting the variables  while creating the channel and fetch it  as the stasis start event happens.
Sometime i get an error variable not found . Please help.

**Comment by grahambrown11** [comment]
Hi @salesAbhin could you provide some more context, where and how are you setting the channel vars?
Is the channel created in the dialplan and the vars set before calling Stasis or did you create the channel from ARI?

**Comment by grahambrown11** [comment]
I managed to do a test and it seems that in both the StasisStart and ChannelStateChange the `channelvars` is never populated this is not an ARI4Java issue this is an Asterisk issue...
However I did find a suitable work around and that is to call the `getChannelVar` method.
I tested with both creating the channel from ARI or the dialplan:
```java
ari.channels().originate("...").setApp("...").addVariables("testv1", "ari-val1").execute();
```
```
exten => ...
same => n,Set(testv1=dialplan-val1)
```
```java
void onStasisStart(StasisStart message) {
    Variable chanVar = ari.channels().getChannelVar(message.getChannel().getId(), "testv1").execute();
    String chanVarString = chanVar.getValue();
    logger.debug("channel var testv1: {}", chanVarString);
    // logs either "ari-val1" or "dialplan-val1"
}
```
