### ISSUE TITLE
protocol_id field in Channel_impl_ari_6_0_0

### ISSUE THREAD

**Issue by hansbacher** [ari4java/ari4java#190]
I saw you added protocol_id for Channel_impl_ari_8_0_0. I am experiencing a problem in 6_0_0 with this property.

Decoding JSON: Unrecognized field "protocol_id" (class ch.loway.oss.ari4java.generated.ari_6_0_0.models.Channel_impl_ari_6_0_0), not marked as ignorable (10 known properties: "state", "language", "connected", "accountcode", "caller", "creationtime", "channelvars", "dialplan", "id", "name"])
 at [Source: (String)"{
  "id": "CHID-5192c3b4-feae-4550-a1af-1da3907cc72c",
  "name": "Local/P-Outbound@P-0000001f;1",
  "state": "Down",
  "protocol_id": "",
  "caller": {
    "name": "",
    "number": "+1111"
  },
  "connected": {
    "name": "",
    "number": "+1111"
  },
  "accountcode": "",
  "dialplan": {
    "context": "MyContext",
    "exten": "P-Outbound",
    "priority": 1,
    "app_name": "AppDial2",
    "app_data": "(Outgoing Line)"
  },
  "creationtime": "2023-01-12T00:04:06.114+"[truncated 27 chars]; line: 5, column: 19] (through reference chain: ch.loway.oss.ari4java.generated.ari_6_0_0.models.Channel_impl_ari_6_0_0["protocol_id"])

**Comment by hansbacher** [comment]
Ok the methods are annotated with @JsonIgnore, I don't know why the exception is thrown nonetheless.

    @JsonIgnore
    public void setProtocol_id(String val) {
        throw new UnsupportedOperationException("Method available from ari_4_1_4");
    }

    @JsonIgnore
    public String getProtocol_id() {
        throw new UnsupportedOperationException("Method available from ari_4_1_4");
    }

**Comment by hansbacher** [comment]
Sorry it was my fault, now I use jackson-databind.version 2.14.1 and it works.

**Comment by solaechea** [comment]
I got the same issue, this was useful, thank you!
