### ISSUE TITLE
Update API to 20.2?

### ISSUE THREAD

**Issue by afonsolage** [ari4java/ari4java#191]
Github Actions seems to be disabled the scheduled run, due to inactivity. So, I'm just pinging to run the CI to check for updates on 20.2

**Comment by grahambrown11** [comment]
Sorry for the late reply, I'll enable the workflow again and release an update soon

**Comment by grahambrown11** [comment]
20.2 still using ARI 8.0.0 so there are no changes, the actions just updated the [Wiki](https://github.com/ari4java/ari4java/wiki/Asterisk-Version-to-ARI-Version) now the list inluces 20.2.x
